# Numpy Array

* ***Notas***:
  - Los arreglos de numpy, pueden ejecutarse mucho más rápido que las listas.
  - Siempre usarlo como `np`.
  - Con arange, nos genera los numeros, pero sin incluir el ultimo.
  - Comparte muchas funciones con la lista original.

In [1]:
import numpy as np

## Definimos unos arreglos

In [5]:
### Definimos unos arreglos
arreglo1 = np.array([1,2,3,4,5,6])
arreglo2 = np.arange(1,7)
lista = [1,2,3,4,5,6]
print(arreglo1)
print(arreglo2)
print(lista)


print(type(arreglo1))
print(type(arreglo2))
print(type(lista))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'list'>


## Similitudes con las listas

In [6]:
### Comparte muchas funciones con las listas normales
print(arreglo1[1:4])
### Esto no modifica el arrglo, solo el orden de impresión
print(arreglo1[::-1])  
### Tambien podemos usar size, pero no hay que poner '()'
print(arreglo1.size)
print(len(arreglo1))

[2 3 4]
[6 5 4 3 2 1]
6
6


## Ordenamiento

In [10]:
### Ordenando
ordenado = sorted(arreglo1)
print("Ordenado:", ordenado)

ordenado_inverso = sorted(arreglo1, reverse=True)
print("OrdenadoInverso:", ordenado_inverso)

Ordenado: [1, 2, 3, 4, 5, 6]
OrdenadoInverso: [6, 5, 4, 3, 2, 1]


## Redimensionamiento

In [11]:
### Tipo de datos del arreglo, tampoco lleva parentesís
### Hay diferentes tipo de enteros, en este caso tenemos int32
print(arreglo1.dtype)

### Redefinir el tamaño del arreglo. Aquí lo refinimos como 2x3
arreglo3 = arreglo1.reshape(2, 3)
print(arreglo3)

int32
[[1 2 3]
 [4 5 6]]


## Modificaciones a un Array

In [12]:
### Aquí agreamos un nuevo valor, pero no modifica al arreglo original, tenemos que asignarlo
arreglo3 = np.append(arreglo3,[7,8,9])
arreglo3 = arreglo3.reshape(3, 3)
print("Arreglo Append:\n",arreglo3)

### Insertar un valor en un index del arreglo, tenemos que asignarlos
### porque tampoco modifica al arreglo original
arreglo3 = np.insert(arreglo3,0,0)
print("Insert:\n",arreglo3)

### Sería mismo caso para el borrado por index, aquí borramos el 9
arreglo3 = np.delete(arreglo3,9)
print("Insert:\n",arreglo3)

Arreglo Append:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Insert:
 [0 1 2 3 4 5 6 7 8 9]
Insert:
 [0 1 2 3 4 5 6 7 8]


## Busquedas

In [13]:
### Ahora busquemos un número en el arreglo
### esto nos devolverá un array con todos los index y su data type
arreglo3 = np.append(arreglo3,0)
results = np.where(arreglo3 == 0)
print("Results:\n",results)

### operaciones vectoriales
### Sumar 1 a todos los elementos
arreglo3 = arreglo3 + 1
print("Suma+1:\n",arreglo3)

Results:
 (array([0, 9], dtype=int64),)
Suma+1:
 [1 2 3 4 5 6 7 8 9 1]


## EJERCICIO

In [18]:
"""
EJERCICIO
"""
### En Numpy todos los tipos de datos deben ser HOMOGENEOS (mismo tipo)
altura = np.array([1.74, 1.8, 1.78, 1.68, 1.78])
peso = np.array([81.4, 88.7, 87.3, 62.7, 81.6])

### Calcular el IMC
### al trabajar con Numpy, esto nos devolverá un solo arreglo
imc = peso/ (altura * altura)

print("\nIMC:", imc)

### Obtener el promedio
print("\nIMC Promedio:", round(imc.mean(), 2))
print("\nIMC Min:", round(imc.min(), 2))
print("\nIMC Max:", round(imc.max(), 2))


IMC: [26.8859823  27.37654321 27.55333922 22.21513605 25.75432395]

IMC Promedio: 25.96

IMC Min: 22.22

IMC Max: 27.55
